### ISSUE TITLE
live coding

### ISSUE THREAD

**Issue by lmsimp** [lgatto/2017-01-18-CAM#3]
@lgatto for the live coding will we be using our own laptops or the one in the teaching room?

**Comment by lgatto** [comment]
We all use the teaching room computers, so that we have the same environment (which is Windows, RStudio, firefox, libreoffice). Otherwise, it becomes very confusing for students.

**Comment by tavareshugo** [comment]
If we're on Windows, shall I use MS Excel for the spreadsheet exercise then? Several of the workshop materials use screenshots from MS Excel, rather than LibreOffice Calc. (also, I assume most people use MS Office)

**Comment by lgatto** [comment]
I am not sure they even have Excel. I always use LibreOffice because that's what I can prepare with on my computer. But it only really matters for the facet tables example towards the end.
